# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

theme: MC
day_night: false
font: 'alegreya'
font_size: L

# SEO

site_type: Person
local_business_type: ''
org_name: ''
description: 'A data science blog and portfolio by Mickaël Canouil'
twitter: 'mickaelcanouil'

# Contact (edit or remove options as required)

email: "mickael.canouil@cnrs.fr"
phone: +33 (0)3 74 00 81 29
address:
  street: |
    EGID - UMR 1283/8199<br>
    Pôle Recherche - 1er étage Aile Ouest<br>
    1, Place de Verdun
  city: LILLE CEDEX
  postcode: '59045'
  country: FRANCE
  country_code: FR
coordinates:
  latitude: '50.61138'
  longitude: '3.03413'
# office_hours:'Monday to Friday, 9:00 to 18:00'
# appointment_url: 'https://calendly.com'
# contact_links:
#   - icon: twitter
#     icon_pack: fab
#     name: Twitter
#     link: 'https://twitter.com/mickaelcanouil/'
#   - icon: linkedin
#     icon_pack: fab
#     name: LinkedIn
#     link: 'https://www.linkedin.com/in/mickaelcanouil/'
#   - icon: github
#     icon_pack: fab
#     name: Github
#     link: 'https://github.com/mcanouil/'

# Site header

main_menu:
  enable: true
  align: r
  show_logo: true
  show_language: false
  show_day_night: false
  show_search: true
  highlight_active_link: true

# Localization

date_format: 'Monday, the 2 of January, 2006'
time_format: '15:04'
address_format: fr-fr

# Site features

highlight: true
highlight_languages:
  - r
  - python
  - latex
  - bash
highlight_style: github
math: false
diagram: false
privacy_pack: false
edit_page:
  repo_url: ''
  content_dir: ''
  repo_branch: main
  editable:
    page: false
    post: false
    book: false
show_related:
  book: true
  page: false
  post: true
  project: true
  publication: true
  event: true
reading_time: true
section_pager: false
docs_section_pager: true
sharing: true
copyright_license:
  enable: true
  allow_derivatives: true
  share_alike: true
  allow_commercial: false
  notice: 'LICENSE: {license}'
abstract_length: 135
plugins_js: []
avatar:
  gravatar: false
  shape: circle
publications:
  date_format: January 2006
  citation_style: apa
projects:
  post_view: 2
  publication_view: 2
  talk_view: 2
breadcrumb:
  page_types:
    book: true
comments:
  provider: ''
  commentable:
    post: true
    book: true
    project: true
    publication: true
    event: true
  disqus:
    shortname: ''
    show_count: true
  commento:
    url: ''
search:
  provider: wowchemy
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: true
map:
  provider: mapnik
  api_key: ''
  zoom: 15
marketing:
  google_analytics: ''
  google_tag_manager: ''
  google_site_verification: ''
  baidu_site_verification: ''
  baidu_tongji: ''
cms:
  branch: master
  local_backend: false
icon:
  pack:
    ai: false
