on:
  push:
    branches:
      - main

name: blogdown

jobs:
  pkgdown:
    runs-on: ubuntu-18.04
    env:
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/bionic/latest
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        id: install-r

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Install pak and blogdown
        run: |
          install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/")
          pak::pkg_install("blogdown")
          blogdown::install_hugo("0.82.0")
        shell: Rscript {0}

      - name: Build and deploy blogdown site
        run: |
          mkdir www
          Rscript -e 'blogdown::build_site(local = FALSE)'
          cd www && find . -type f -exec curl --fail --silent --max-time 10 --retry 4 --user ${{secrets.FTP_USER}}:${{secrets.FTP_PASSWORD}} --ftp-create-dirs -T {} ftp://${{secrets.FTP_URL}}/www/dev/{} \;

