name: Quarto Render

on:
  push:
    branches:
      - main
    paths-ignore:
      - "_site/**"
      - "_freeze/**"
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  quarto-render-main:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - if: github.event_name == 'push'
        uses: actions/checkout@v3
      - if: github.event_name == 'pull_request'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: ./.github/actions/quarto.yml
        with:
          version: pre-release
      - name: Commit/Push to Pull Request
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add _site/*
          git add _freeze/*
          git commit -m 'ci: quarto rautomatic renderering' || echo "No changes to commit"
          git push
      - name: Create Pull Request
        if: github.event_name == 'push'
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "ci: automatic website rendering with latest Quarto"
          signoff: false
          branch: ci/latest-quarto-updates
          delete-branch: true
          title: "ci: automatic website rendering with latest Quarto"
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          committer: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
